# Generated by Django 3.0.3 on 2020-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='posteo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='feha de publicación')),
                ('contenido', models.CharField(max_length=4000, verbose_name='contenido del post')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('autor', models.CharField(max_length=40, verbose_name='autor del post')),
            ],
        ),
        migrations.DeleteModel(
            name='posteos',
        ),
    ]
