# Generated by Django 3.0.3 on 2020-06-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20200618_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(default='Generico', max_length=40, verbose_name='Titulo para el post'),
            preserve_default=False,
        ),
    ]
