# Generated by Django 3.0.3 on 2020-06-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_posteo_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='feha de publicación')),
                ('contenido', models.CharField(max_length=160, verbose_name='contenido del post')),
                ('autor', models.CharField(max_length=40, verbose_name='autor del post')),
            ],
        ),
    ]
