# Generated by Django 3.0.3 on 2020-06-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='comunicados',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='feha del comunicado')),
                ('titulo', models.CharField(max_length=40, verbose_name='Titulo para el comunicado')),
                ('contenido', models.CharField(max_length=4000, verbose_name='contenido del comunicado')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('autor', models.CharField(max_length=40, verbose_name='autor del comunicado')),
            ],
        ),
    ]
