# Generated by Django 3.0.3 on 2020-06-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_comunicados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comunicados',
            new_name='comunicado',
        ),
    ]
