# Generated by Django 3.1.5 on 2021-07-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_auto_20200630_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='img',
            field=models.CharField(blank=True, max_length=400, verbose_name='Url de la imagen'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='img',
            field=models.CharField(blank=True, max_length=400, verbose_name='Url de la imagen'),
        ),
    ]
